[package]
name = "dope-fiber"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
exclude = ["tests"]

[dependencies]
dope.workspace = true
dope-gen.workspace = true
libc.workspace = true
o3.workspace = true
pin-project.workspace = true
transport = { package = "dope-net", version = "0.15.0", path = "../net" }

[dev-dependencies]
dope-test = { path = "../test" }
