[package]
name = "dope"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
dope-core.workspace = true
dope-net.workspace = true
libc.workspace = true
o3.workspace = true
pin-project.workspace = true
siphasher.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
io-uring.workspace = true

[dev-dependencies]
dope-extra = { path = "../extra" }
dope-fiber = { path = "../fiber" }
dope-gen = { path = "../gen" }

[target.'cfg(target_os = "linux")'.dev-dependencies]
io-uring.workspace = true
libc.workspace = true
