[package]
name = "dope"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
exclude = ["tests"]

[dependencies]
core = { package = "dope-core", version = "0.15.0", path = "../core" }
manifold = { package = "dope-manifold", version = "0.15.0", path = "../manifold" }
net = { package = "dope-net", version = "0.15.0", path = "../net" }
runtime = { package = "dope-runtime", version = "0.15.0", path = "../runtime" }
