[package]
name = "dope-test"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
description = "Shared integration-test support for dope consumers"
repository.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
dope.workspace = true
dope-core.workspace = true
dope-fiber.workspace = true
dope-gen.workspace = true
o3.workspace = true
libc.workspace = true
pin-project.workspace = true
