[package]
name = "dope-dns"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Bounded TTL-aware DNS discovery for dope services"
repository.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
exclude = ["tests"]

[dependencies]
dope.workspace = true
dope-gen.workspace = true
o3.workspace = true
pin-project.workspace = true

[dev-dependencies]
dope-fiber.workspace = true
