[package]
name = "dope-extra"
edition.workspace = true
version.workspace = true
description = "dope launcher, harness, and blocking helpers"
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
dope.workspace = true
dope-fiber.workspace = true
dope-gen.workspace = true
pin-project.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
dope-test.workspace = true
o3.workspace = true
