[package]
name = "dope-manifold"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
license.workspace = true
authors.workspace = true
exclude = ["tests"]

[dependencies]
dope-core.workspace = true
dope-net.workspace = true
dope-runtime.workspace = true
libc.workspace = true
o3.workspace = true
pin-project.workspace = true

[dev-dependencies]
dope-fiber = { path = "../fiber" }
dope-gen = { path = "../gen" }
dope-test = { path = "../test" }
